### ISSUE TITLE
jekyll/document (LoadError)

### ISSUE THREAD

**Issue by sohaninfo** [ContainX/openstack4j.com#23]
I am newbie to jekyll and ruby. I was trying to update site for Magnum APIs. Here follows the env details:
ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]
gem -v
2.6.11
jekyll -v
jekyll 1.4.3

The command bundle install was successful. But when I tried to run jekyll serve -w, I got error:  jekyll/document (LoadError).

Please help and give some pointers.

Error logs:
jekyll serve -w
Configuration file: /home/compute/src/openstack4j.com/_config.yml
/home/compute/src/openstack4j.com/_plugins/sitemap_generastor.rb:13:in `require': cannot load such file -- jekyll/document (LoadError)
	from /home/compute/src/openstack4j.com/_plugins/sitemap_generastor.rb:13:in `<top (required)>'
	from /home/compute/.rvm/gems/ruby-2.1.2/gems/jekyll-1.4.3/lib/jekyll/site.rb:77:in `require'
	from /home/compute/.rvm/gems/ruby-2.1.2/gems/jekyll-1.4.3/lib/jekyll/site.rb:77:in `block (2 levels) in setup'
	from /home/compute/.rvm/gems/ruby-2.1.2/gems/jekyll-1.4.3/lib/jekyll/site.rb:76:in `each'
	from /home/compute/.rvm/gems/ruby-2.1.2/gems/jekyll-1.4.3/lib/jekyll/site.rb:76:in `block in setup'
	from /home/compute/.rvm/gems/ruby-2.1.2/gems/jekyll-1.4.3/lib/jekyll/site.rb:75:in `each'
	from /home/compute/.rvm/gems/ruby-2.1.2/gems/jekyll-1.4.3/lib/jekyll/site.rb:75:in `setup'
	from /home/compute/.rvm/gems/ruby-2.1.2/gems/jekyll-1.4.3/lib/jekyll/site.rb:29:in `initialize'
	from /home/compute/.rvm/gems/ruby-2.1.2/gems/jekyll-1.4.3/lib/jekyll/commands/build.rb:5:in `new'
	from /home/compute/.rvm/gems/ruby-2.1.2/gems/jekyll-1.4.3/lib/jekyll/commands/build.rb:5:in `process'
	from /home/compute/.rvm/gems/ruby-2.1.2/gems/jekyll-1.4.3/bin/jekyll:97:in `block (2 levels) in <top (required)>'
	from /home/compute/.rvm/gems/ruby-2.1.2/gems/commander-4.1.6/lib/commander/command.rb:180:in `call'
	from /home/compute/.rvm/gems/ruby-2.1.2/gems/commander-4.1.6/lib/commander/command.rb:180:in `call'
	from /home/compute/.rvm/gems/ruby-2.1.2/gems/commander-4.1.6/lib/commander/command.rb:155:in `run'
	from /home/compute/.rvm/gems/ruby-2.1.2/gems/commander-4.1.6/lib/commander/runner.rb:422:in `run_active_command'
	from /home/compute/.rvm/gems/ruby-2.1.2/gems/commander-4.1.6/lib/commander/runner.rb:66:in `run!'
	from /home/compute/.rvm/gems/ruby-2.1.2/gems/commander-4.1.6/lib/commander/delegates.rb:8:in `run!'
	from /home/compute/.rvm/gems/ruby-2.1.2/gems/commander-4.1.6/lib/commander/import.rb:10:in `block in <top (required)>'

**Comment by auhlig** [comment]
Sorry @sohaninfo. I missed that issue. Maybe you could try using the [docker container](https://github.com/ContainX/openstack4j.com/blob/master/README.md#run-with-docker).

**Comment by sohaninfo** [comment]
hi Arno,

Thank you very much. I will use the container.

Regards,
Sohan

**Comment by sohaninfo** [comment]
I tried container. It works well. Closing this issue.
