### ISSUE TITLE
Javadoc not accessible

### ISSUE THREAD

**Issue by vinodborole** [ContainX/openstack4j.com#27]
Java doc not accessible - http://www.openstack4j.com/javadoc

@auhlig do you know how to fix this?

**Comment by auhlig** [comment]
Must be related to #25 :-/ I'll look into it.

**Comment by auhlig** [comment]
Just checked quickly. It works or me(TM) with the latest containerized version which includes #25 via `docker run -p 80:80 pacesys/openstack4j.com:latest`. 
Edit: And website javadoc works for me again. Could you also check @vinodborole? Will take another look tomorrow.

**Comment by auhlig** [comment]
The javadoc seems to be unavailable for a short time while deploying a new version. Apart from that it works.
